enum Color { BLACK, RED, BLUE, ORANGE, GREEN }

enum PointMarker { CIRCLE, STAR, SQUARE, TRIANGLE, PUSH_PIN }

enum LineMarker { DASHED, DOTTED, SOLID }

enum Geometry { LINE, POINT, POLYGONE }

enum UsageType { BUSINNES, ENTERTAINMENT, EDUCATION, RESIDENCE, GOVERNMENT }

enum UtilityType { ELECTRICAL, FIBER_OPTIC, WATER, GAS }